simple_shop/goods/urls.py
from django.urls import path

from . import views

app_name = 'goods'

urlpatterns = [
    path('item/<str:name_slug>/', views.item_page, name='item_page'),
    path('cart/', views.cart, name='cart'),
    path('success/', views.success_order, name='success'),
    path('<str:item_type_slug>/', views.items_by_category, name='category'),
]

simple_shop/index_page/urls.py
from django.urls import path

from . import views

app_name = 'index_page'

urlpatterns = [
    path('', views.index, name='index')
]

simple_shop/simple_shop/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  re_path(r'^accounts/',
                          include('django.contrib.auth.urls')),
                  path('shop/', include('goods.urls')),
                  path('', include('index_page.urls'))
              ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

simple_shop/goods/models.py
from django.core.validators import MinValueValidator, \
    MaxValueValidator
from django.db import models

from django.utils import timezone

# from users.models import User


class Item(models.Model):
    """
    Модель наименования товара
    """
    name = models.CharField(max_length=64, unique=True)
    image = models.ImageField(upload_to='photos/')
    description = models.CharField(max_length=400)
    type = models.ForeignKey('ItemType', on_delete=models.CASCADE)
    name_slug = models.SlugField()
    add_time = models.DateTimeField(default = timezone.now)

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    def __str__(self):
        return self.name


class ItemType(models.Model):
    """
    Модель категории товара, поле name используется для заголовка
    страницы категории
    """
    slug = models.CharField(max_length=32, unique=True)
    display_name = models.CharField(max_length=32, default='NewName', unique=True)

    class Meta:
        verbose_name = 'категория товара'
        verbose_name_plural = 'категории товара'

    def __str__(self):
        return self.slug


class Review(models.Model):
    """
    Модель формирования отзыва на товар
    """
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE,
                             related_name='reviews')
    text = models.CharField(max_length=200)
    rating = models.PositiveIntegerField(
        default=1,validators=[MinValueValidator(1),
                              MaxValueValidator(5)]
    )


class Order(models.Model):
    """
    Модель формирования заказа
    """
    buyer = models.ForeignKey('users.User', on_delete=models.CASCADE,
                              verbose_name='покупатель')
    items = models.ManyToManyField(Item, through='OrderPosition')
    date = models.DateTimeField(default=timezone.now,
                                verbose_name='дата создания')
    is_closed = models.BooleanField(default=False,
                                    verbose_name='сформирован')

    class Meta:
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f"Заказ № {self.pk}"


class OrderPosition(models.Model):
    """
    Промежуточная модель m2m (Order <- OrderPosition -> Item)
    для хранения данных о количестве единиц
    товара в заказе (поле quantity)
    """
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    class Meta:
        verbose_name = 'позиция'
        verbose_name_plural = 'позиции'

    def __str__(self):
        return f"{self.item}, {self.quantity} шт."

simple_shop/goods/forms.py
from django import forms
from .models import Review

RATING_CHOICES = [
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
]

class ReviewCreateForm(forms.ModelForm):
    """
    Форма создания отзыва на странице наименования товара (item page)
    """
    rating = forms.ChoiceField(choices=RATING_CHOICES,
                               widget=forms.RadioSelect())

    class Meta:
        model = Review
        fields = ['text', 'rating']
        exclude = ['author', 'reviewed_item']
        widgets = {
            'text': forms.Textarea(attrs={
                    'id': "content",
                    'placeholder': "Содержание",
                    'class': 'form-control',
                    }),
        }

simple_shop/goods/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from django.db.models import ObjectDoesNotExist

from .models import Item, Review, Order
from .forms import ReviewCreateForm

CATEGORY_ITEMS_COUNT = 6  # Items for page in items_by_category view


@login_required
def cart(request):
    """
    Страница корзины. Считывает из запроса (request) поля
    'order_id' (id заказа) и 'position_id' (id товара, добавляемого
    в корзину).
    """
    template = 'goods/cart.html'
    pos_id = request.POST.get('position_id')
    user = request.user

    try:
        order_id = request.session.get('order_id')
        order = Order.objects.get(id=order_id, is_closed=False)
    except ObjectDoesNotExist:
        order = Order.objects.create(buyer=user)
        request.session['order_id'] = f'{order.id}'

    if request.method == 'GET':
        context = {'order': order}
        return render(request, template, context)

    if request.method == 'POST':
        position = Item.objects.get(id=pos_id)

        try:
            pos_record = order.orderposition_set.get(item_id=pos_id)
            pos_record.quantity = pos_record.quantity + 1
            pos_record.save()
        except ObjectDoesNotExist:
            order.items.add(position)
            order.save()

        return HttpResponseRedirect(reverse('goods:cart'))


def success_order(request):
    """
    Страница завершения заказа. Считывает из request поле 'order_id'
    с идентификатором заказа. Закрывает заказ, делает его недоступным
    для дальнейшего наполнения.
    """
    template = 'goods/success_order.html'
    order_id = request.session.get('order_id')
    context = {'order_id': order_id}
    order_record = Order.objects.filter(id=order_id, )
    order_record.update(is_closed=True)
    request.session.pop('order_id')

    return render(request, template, context)


def items_by_category(request, item_type_slug):
    """
    Страница категории с пагинацией
    :param request: стандартный запрос
    :param item_type_slug: идентификатор категории,
        соответствует полю models.ItemType.item_type
    """
    page_num = int(request.GET.get('page', 1))
    count = CATEGORY_ITEMS_COUNT
    template = 'goods/items_by_cat.html'
    items = Item.objects.all().select_related('type').filter \
        (type__slug=item_type_slug).order_by('-add_time')
    category = items.first().type.display_name
    print('cat is:', category)
    paginator = Paginator(items, count)
    page = paginator.get_page(page_num)
    context = {
        'items': items,
        'category': category,
        'page': page
    }
    return render(request, template, context)

def item_page(request, name_slug):
    """
    Страница наименования товара
    :param request: стандартный запрос
    :param name_slug: слагифицированное наименование товара,
        соответствует полю models.Item.name_slug
    """
    template = 'goods/item.html'
    position = Item.objects.all().get(name_slug=name_slug)

    if request.method == 'POST':
        review_form = ReviewCreateForm(request.POST)
        if review_form.is_valid():
            text = review_form.cleaned_data['text']
            rating = review_form.cleaned_data['rating']
            author = request.user
            new_review = Review.objects.create(
                author=author, item=position,
                text=text, rating=rating
            )
            return redirect('goods:item_page', f'{name_slug}')
    else:
        review_form = ReviewCreateForm()

    context = {
        'position': position,
        'form': review_form,
    }
    return render(request, template, context)

simple_shop/templates/goods/cart.html
{% extends 'goods/empty_section.html' %}
<!DOCTYPE html>

{% block main %}
<div class="container mt-3">

  <div class="row">
    <div class="col-lg-6 col-md-9 col-sm-12 order-md-2 mb-4">
      <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Заказ № {{ order.id }}. Ваша корзина</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.all|length }}</span>
      </h4>
      <ul class="list-group mb-3">
        {% for order_position in order.orderposition_set.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0">{{ order_position.item.name }}</h6>
            <small class="text-muted">{{ order_position.item.description }}</small>
          </div>
          <span class="text-muted">{{ order_position.quantity }}</span>

        </li>
        {% endfor %}

      </ul>

      <form class="card p-2" action="{% url 'goods:success' %}">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
        <button type="submit" class="btn btn-secondary">Заказать</button>
      </form>
    </div>
  </div>


</div>
{% endblock %}

simple_shop/templates/goods/empty_section.html
{% block head %}
{% load static %}{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Graduation Work</title>
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="" data-gr-c-s-loaded="true">
{% endblock %}

{% block nav %}
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'index_page:index' %}">Просто магазин</a>
  <img src="{% static 'logo.svg' %}" alt="" width="42" height="42">
  <button class="navbar-toggler" type="button" data-toggle="collapse"
          data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault"
          aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index_page:index' %}">
          Главная</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Гаджеты</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'goods:category' 'phones' %}">
            Сматрфоны</a>
          <a class="dropdown-item" href="{% url 'goods:category' 'headphones' %}">
            Наушники </a>
          <a class="dropdown-item" href="{% url 'goods:category' 'tablets' %}">
            Планшеты </a>
        </div>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'goods:category' 'accessoires' %}">
          Аксесcуары</a>
      </li>

    </ul>
    {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link">
          Привет, {{ user.first_name }}</a>
      </li>
    </ul>
    {% endif %}

    <a class="btn btn-outline-success my-2 my-sm-0" role="button"
       href="{% url 'goods:cart' %}">
      Корзина</a>

    {% if user.is_authenticated %}
    <a class="btn btn-outline-success my-2 my-sm-0" role="button"
       href="{% url 'logout' %}">
      Выйти</a>
    {% else %}
    <a class="btn btn-outline-success my-2 my-sm-0" role="button"
       href="{% url 'login' %}">
      Войти</a>
    {% endif %}
  </div>
</nav>
{% endblock %}


{% block main %}
<main role="main">

  <div class="container">
    <!-- Example row of columns -->


    <div class="alert alert-dark" role="alert">
      Тут пока ничего нет!
    </div>


  </div> <!-- /container -->

</main>
{% endblock %}

{% block footer %}
<hr>
<footer class="container">
  <p>© Просто магазин 2020</p>
</footer>

<script src="{% static 'jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>
{% endblock %}

simple_shop/templates/goods/index.html
{% extends 'goods/empty_section.html' %}
{% load in_category %}{% load static %}
{% block main %}
<main role="main">

  <div class="jumbotron">
    <div class="container">
      <h1 class="display-4">Добро пожаловать на сайт просто магазина</h1>

    </div>
  </div>

  {% for offer in offers %}
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-4">{{ offer.headline }}</h1>
      <p>{{ offer.sub_line }}</p>
    </div>
  </div>

  <div class="container mb-5">
    <!-- Example row of columns -->
    <div class="row">
      {% for item in items|in_category:offer.category_id %}
      <div class="col-md-4">
        <h2>{{ item.name }}</h2>
        {% url 'goods:item_page' item.name_slug as item_url %}
        <a href="{{ item_url }}">
          <img src="{% get_media_prefix %}{{ item.image }}" width="180">
        </a>
        <form method="post" action="{% url 'goods:cart' %}">
          <input type="hidden" name="csrfmiddlewaretoken"
                 value="{{ csrf_token }}">
          <input type="hidden" name="position_id" value="{{ item.id }}">
          <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
        </form>
      </div>
      {% endfor %}

    </div>

  </div> <!-- /container -->
  {% endfor %}

</main>
{% endblock %}

simple_shop/templates/goods/item.html
{% extends 'goods/empty_section.html' %}{% load static %}
{% block main %}{% load in_stars %}
<main role="main">


  <div class="container mt-3">
    <!-- Example row of columns -->

    <div class="row">

      <div class="col-md-12">

        <h2>{{ position.name }}</h2>

        <img src="{% get_media_prefix %}{{ position.image }}" width="120">

        <p>{{ position.description }}</p>
        <form method="post" action="{% url 'goods:cart' %}">
          <input type="hidden" name="csrfmiddlewaretoken"
                 value="{{ csrf_token }}">
          <input type="hidden" name="position_id" value="{{ position.id }}">
          <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
        </form>
      </div>

    </div>
    <hr>
        {% if position.reviews.all %}
            {% for review in position.reviews.all %}
                {{ review.rating|in_stars }} <span>{{ review.author.first_name }}</span>
                <p> {{ review.text}}</p>
            {% endfor %}
        {% else%}
            <p>Пока отзывов на товар нет. Значит, Ваш будет первым!</p>
        {% endif %}
        <hr>

    {% if user.is_authenticated %}
    <div class="row">

      <div class="col-lg-6 col-md-8 col-sm-12">
        <h4>Оставьте отзыв:</h4>

        <form method="post">
          <input type="hidden" name="csrfmiddlewaretoken"
                 value="{{ csrf_token }}">
          <div class="form-group">
            <label for="content">Содержание</label><br>
            {{ form.text }}
          </div>
          {% for radio in form.rating %}
          <div class="form-check">
            {{ radio }}
          </div>
          {% endfor %}

          <button type="submit" class="btn btn-primary">Оставить</button>
        </form>
      </div>
    </div>
    {% else %}
    <p>Зарегистрируйтесь, чтобы оставить отзыв</p>
    {% endif %}
  </div> <!-- /container -->


</main>
{% endblock %}

simple_shop/templates/goods/items_by_cat.html
{% extends 'goods/empty_section.html' %}{% load static %}

{% block main %}
<main role="main">

  <div class="container">
    <!-- Example row of columns -->

    <h1>{{ category }}</h1>

    <div class="row">
        {% for item in page %}


      <div class="col-md-4">

        <h2>{{ item.name }}</h2>

        <a href="{% url 'goods:item_page' item.name_slug %}">

          <img src="{% get_media_prefix %}{{ item.image }}" width="180">

        </a>
        <p>{{ item.description }}</p>

        <form method="post" action="{% url 'goods:cart' %}">
          <input type="hidden" name="csrfmiddlewaretoken"
                 value="{{ csrf_token }}">
          <input type="hidden" name="position_id" value="{{ item.id }}">
          <input type="submit" class="btn btn-secondary" value="Добавить в корзину »">
        </form>
      </div>
    {% endfor %}



    </div> <!-- /container -->

    <hr>
    <div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a class="btn btn-secondary" role="button" href="?page=1">&laquo; В начало</a>
            <a class="btn btn-secondary" role="button" href="?page={{ page.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page.number }} из {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a class="btn btn-secondary" role="button" href="?page={{ page.next_page_number }}">Следующая</a>
            <a class="btn btn-secondary" role="button" href="?page={{ page.paginator.num_pages }}">В конец &raquo;</a>
        {% endif %}
    </span>
</div>

  </div>
</main>
{% endblock %}

simple_shop/templates/goods/login.html
{% extends 'goods/empty_section.html' %}
{% block head %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Graduation Work</title>
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'main.css' %}">
  <link rel="stylesheet" href="{% static 'login.css' %}">
</head>
<body class="text-center" data-gr-c-s-loaded="true">
{% endblock %}

{% block main %}

<form class="form-signin">
  <input type="hidden" name="next" value="">
  <img class="mb-4" src="{% static 'logo.svg' %}" alt="" width="72" height="72">


  <h1 class="h3 mb-3 font-weight-normal">Вход</h1>
  <label for="inputEmail" class="sr-only">Email</label>
  <input type="email" id="inputEmail" class="form-control" placeholder="Email" name="username"
         value="" required="" autofocus="" data-cip-id="inputEmail">
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" class="form-control" placeholder="Пароль"
         name="password" required="" data-cip-id="inputPassword">

  <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
  <p class="mt-5 mb-3 text-muted">© Просто магазин 2020</p>
</form>
{% endblock %}
{% block footer %}
<script src="{% static 'jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.css' %}"></script>
</body>
</html>
{% endblock %}

simple_shop/templates/goods/success_order.html
{% extends 'goods/empty_section.html' %}{% load static %}
{% block head %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Graduation Work</title>
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'main.css' %}">
  <link rel="stylesheet" href="{% static 'login.css' %}">
</head>
<body class="text-center" data-gr-c-s-loaded="true">
{% endblock %}

{% block main %}

<form class="form-signin">

  <h1 class="h3 mb-3 font-weight-normal">Заказ № {{ order_id }} успешно создан!</h1>
  <img class="mb-4" src="{% static 'logo.svg' %}" alt="" width="72" height="72">
  <p>Чтобы вернуться к выбору товара, воспользуйтесь пунктами верхнего меню.</p>
  <p>Или закончите работу с магазином, воспользовавшись кнопкой «Выйти».</p>
  <p>Будем рады видеть вас снова!</p>


  <p class="mt-5 mb-3 text-muted">© Просто магазин 2020</p>
</form>
{% endblock %}

{% block footer %}
<script src="{% static 'jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'popper.min.js' %}"></script>
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>
{% endblock %}